<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="W. Europe Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="ITINBAI-DW0014"><DocLocation><![CDATA[\\Itseelm-nt0034\ampes1$\Desktop\RegressionPack0.4\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res36]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default_0.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Excel Sheet Import]]></Obj>
<Details ><![CDATA[Excel Sheet  Applications Import to Applications operation Done Succefully]]></Details>
<Time><![CDATA[6/28/2016 - 15:15:54]]></Time>
<TimeTick>1467119754</TimeTick>
<NodeArgs eType="User" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Excel Sheet Import]]></Disp>
</NodeArgs>
</Step>
<Action rID="T4">
<AName><![CDATA[Driver]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/28/2016 - 15:15:57]]></Time>
<TimeTick>1467119757</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[Excel Sheet Import]]></Obj>
<Details ><![CDATA[Excel Sheet  Global Import to Global operation Done Succefully]]></Details>
<Time><![CDATA[6/28/2016 - 15:15:57]]></Time>
<TimeTick>1467119757</TimeTick>
<NodeArgs eType="User" icon="3" nRep="10" status="Passed" >
<Disp><![CDATA[Excel Sheet Import]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:01]]></Time>
<TimeTick>1467119761</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[OWCS.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:01]]></Time>
<TimeTick>1467119761</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" >
<Disp><![CDATA[OWCS.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:02]]></Time>
<TimeTick>1467119762</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:02]]></Time>
<TimeTick>1467119762</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" status="Passed" >
<Disp><![CDATA[Run "firefox.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="6" nRep="16" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OWCS.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:27]]></Time>
<TimeTick>1467119787</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="18" >
<Disp><![CDATA[OWCS.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OWCS.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:27]]></Time>
<TimeTick>1467119787</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="19" >
<Disp><![CDATA[OWCS.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj ><![CDATA[CheckBrowserExist]]></Obj>
<Details ><![CDATA[Browser exist]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:27]]></Time>
<TimeTick>1467119787</TimeTick>
<NodeArgs eType="User" icon="3" nRep="20" >
<Disp><![CDATA[CheckBrowserExist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:27]]></Time>
<TimeTick>1467119787</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[NWPFE.Refresh All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:27]]></Time>
<TimeTick>1467119787</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="23" >
<Disp><![CDATA[NWPFE.Refresh All Tabs]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="22" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:48]]></Time>
<TimeTick>1467119808</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:48]]></Time>
<TimeTick>1467119808</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[txtUsername.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:48]]></Time>
<TimeTick>1467119808</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" >
<Disp><![CDATA[txtUsername.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[txtUsername.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:48]]></Time>
<TimeTick>1467119808</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" >
<Disp><![CDATA[txtUsername.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[txtUsername.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["fwadmin"]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:48]]></Time>
<TimeTick>1467119808</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="31" >
<Disp><![CDATA[txtUsername.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="26" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="25" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[TakeAction]]></Obj>
<Details ><![CDATA[WebEdit  - Username
Entered - fwadmin]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:48]]></Time>
<TimeTick>1467119808</TimeTick>
<NodeArgs eType="User" icon="3" nRep="32" >
<Disp><![CDATA[TakeAction]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:49]]></Time>
<TimeTick>1467119809</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:49]]></Time>
<TimeTick>1467119809</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[txtPassword.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:49]]></Time>
<TimeTick>1467119809</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="36" >
<Disp><![CDATA[txtPassword.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[txtPassword.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:49]]></Time>
<TimeTick>1467119809</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="38" >
<Disp><![CDATA[txtPassword.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[txtPassword.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["xceladmin"]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:49]]></Time>
<TimeTick>1467119809</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="40" >
<Disp><![CDATA[txtPassword.SetSecure]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="35" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="34" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[TakeAction]]></Obj>
<Details ><![CDATA[WebEdit  - Password
Entered - xceladmin]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:49]]></Time>
<TimeTick>1467119809</TimeTick>
<NodeArgs eType="User" icon="3" nRep="41" >
<Disp><![CDATA[TakeAction]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:51]]></Time>
<TimeTick>1467119811</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:51]]></Time>
<TimeTick>1467119811</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[eleLogIn.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:51]]></Time>
<TimeTick>1467119811</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" >
<Disp><![CDATA[eleLogIn.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[eleLogIn.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:51]]></Time>
<TimeTick>1467119811</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" >
<Disp><![CDATA[eleLogIn.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="44" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="43" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj ><![CDATA[TakeAction]]></Obj>
<Details ><![CDATA[WebElement   - LogIn
clicked - ]]></Details>
<Time><![CDATA[6/28/2016 - 15:16:51]]></Time>
<TimeTick>1467119811</TimeTick>
<NodeArgs eType="User" icon="3" nRep="48" >
<Disp><![CDATA[TakeAction]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:01]]></Time>
<TimeTick>1467119821</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:01]]></Time>
<TimeTick>1467119821</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[eleSiteIcon.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:01]]></Time>
<TimeTick>1467119821</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" >
<Disp><![CDATA[eleSiteIcon.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[eleSiteIcon.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:01]]></Time>
<TimeTick>1467119821</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="54" >
<Disp><![CDATA[eleSiteIcon.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[eleIkeaGlobal.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:03]]></Time>
<TimeTick>1467119823</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="55" >
<Disp><![CDATA[eleIkeaGlobal.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="51" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="50" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[SelectSite]]></Obj>
<Details ><![CDATA[eleIkeaGlobal  selected.]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:07]]></Time>
<TimeTick>1467119827</TimeTick>
<NodeArgs eType="User" icon="3" nRep="57" >
<Disp><![CDATA[SelectSite]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:07]]></Time>
<TimeTick>1467119827</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:07]]></Time>
<TimeTick>1467119827</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[imgContributor.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:07]]></Time>
<TimeTick>1467119827</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="60" >
<Disp><![CDATA[imgContributor.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:15]]></Time>
<TimeTick>1467119835</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[eleContent.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:16]]></Time>
<TimeTick>1467119836</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" >
<Disp><![CDATA[eleContent.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[eleAdminSite.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:36]]></Time>
<TimeTick>1467119856</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="191" >
<Disp><![CDATA[eleAdminSite.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="76" >
<Disp><![CDATA[Frame]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[XcelBanner]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:56]]></Time>
<TimeTick>1467119876</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[eleNewTab.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:57]]></Time>
<TimeTick>1467119877</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="362" >
<Disp><![CDATA[eleNewTab.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="361" >
<Disp><![CDATA[XcelBanner]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="59" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="58" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[SelectIcon]]></Obj>
<Details ><![CDATA[imgContributor  selected.]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:57]]></Time>
<TimeTick>1467119877</TimeTick>
<NodeArgs eType="User" icon="3" nRep="363" >
<Disp><![CDATA[SelectIcon]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:57]]></Time>
<TimeTick>1467119877</TimeTick>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:57]]></Time>
<TimeTick>1467119877</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:57]]></Time>
<TimeTick>1467119877</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[txtSearchtxtBox.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:57]]></Time>
<TimeTick>1467119877</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="368" >
<Disp><![CDATA[txtSearchtxtBox.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="367" >
<Disp><![CDATA[Frame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="366" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="365" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj ><![CDATA[CheckObject]]></Obj>
<Details ><![CDATA[WebEdit  - SearchtxtBoxExist]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:57]]></Time>
<TimeTick>1467119877</TimeTick>
<NodeArgs eType="User" icon="3" nRep="369" >
<Disp><![CDATA[CheckObject]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:58]]></Time>
<TimeTick>1467119878</TimeTick>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:58]]></Time>
<TimeTick>1467119878</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:58]]></Time>
<TimeTick>1467119878</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[txtSearchtxtBox.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:58]]></Time>
<TimeTick>1467119878</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="373" >
<Disp><![CDATA[txtSearchtxtBox.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[txtSearchtxtBox.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:58]]></Time>
<TimeTick>1467119878</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="375" >
<Disp><![CDATA[txtSearchtxtBox.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[txtSearchtxtBox.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["TestAutoEA"]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:58]]></Time>
<TimeTick>1467119878</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="377" >
<Disp><![CDATA[txtSearchtxtBox.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="372" >
<Disp><![CDATA[Frame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="371" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="370" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[TakeAction]]></Obj>
<Details ><![CDATA[WebEdit  - SearchtxtBox
Entered - TestAutoEA]]></Details>
<Time><![CDATA[6/28/2016 - 15:17:58]]></Time>
<TimeTick>1467119878</TimeTick>
<NodeArgs eType="User" icon="3" nRep="378" >
<Disp><![CDATA[TakeAction]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:01]]></Time>
<TimeTick>1467119881</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:01]]></Time>
<TimeTick>1467119881</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:01]]></Time>
<TimeTick>1467119881</TimeTick>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[imgSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:01]]></Time>
<TimeTick>1467119881</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="382" >
<Disp><![CDATA[imgSearch.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="381" >
<Disp><![CDATA[Frame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="380" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="379" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA[CheckObject]]></Obj>
<Details ><![CDATA[WebImage  - SearchExist]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:01]]></Time>
<TimeTick>1467119881</TimeTick>
<NodeArgs eType="User" icon="3" nRep="383" >
<Disp><![CDATA[CheckObject]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:05]]></Time>
<TimeTick>1467119885</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:05]]></Time>
<TimeTick>1467119885</TimeTick>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:05]]></Time>
<TimeTick>1467119885</TimeTick>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[imgSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:05]]></Time>
<TimeTick>1467119885</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="387" >
<Disp><![CDATA[imgSearch.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[imgSearch.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:05]]></Time>
<TimeTick>1467119885</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="389" >
<Disp><![CDATA[imgSearch.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="386" >
<Disp><![CDATA[Frame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="385" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="384" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj ><![CDATA[TakeAction]]></Obj>
<Details ><![CDATA[WebImage  - Search
clicked - ]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:05]]></Time>
<TimeTick>1467119885</TimeTick>
<NodeArgs eType="User" icon="3" nRep="390" >
<Disp><![CDATA[TakeAction]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:08]]></Time>
<TimeTick>1467119888</TimeTick>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:08]]></Time>
<TimeTick>1467119888</TimeTick>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:08]]></Time>
<TimeTick>1467119888</TimeTick>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[imgSearch.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:08]]></Time>
<TimeTick>1467119888</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="395" >
<Disp><![CDATA[imgSearch.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[eleShowResultskeyword.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:13]]></Time>
<TimeTick>1467119893</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="396" >
<Disp><![CDATA[eleShowResultskeyword.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[eleSearchResultAsset.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:13]]></Time>
<TimeTick>1467119893</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="397" >
<Disp><![CDATA[eleSearchResultAsset.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[[ TestAutoEA ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:16]]></Time>
<TimeTick>1467119896</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="398" >
<Disp><![CDATA[[ TestAutoEA ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[eleNoresultsfound.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:16]]></Time>
<TimeTick>1467119896</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="399" >
<Disp><![CDATA[eleNoresultsfound.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="394" >
<Disp><![CDATA[Frame]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="393" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="392" >
<Disp><![CDATA[OWCS]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">
<Obj ><![CDATA[VerifyAsset]]></Obj>
<Details ><![CDATA[Asset  - TestAutoEAis not Exist ]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:16]]></Time>
<TimeTick>1467119896</TimeTick>
<NodeArgs eType="User" icon="3" nRep="400" >
<Disp><![CDATA[VerifyAsset]]></Disp>
</NodeArgs>
</Step>
<Step rID="T80">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:17]]></Time>
<TimeTick>1467119897</TimeTick>
<Step rID="T81">
<Obj plainTxt="False" ><![CDATA[OWCS]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:17]]></Time>
<TimeTick>1467119897</TimeTick>
<Step rID="T82">
<Obj plainTxt="False" ><![CDATA[Frame]]></Obj>
<Details plainTxt="False" ><![CDATA[Frame]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:17]]></Time>
<TimeTick>1467119897</TimeTick>
<Step rID="T83">
<Obj plainTxt="False" ><![CDATA[eleCloseAsset.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[6/28/2016 - 15:18:17]]></Time>