<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="W. Europe Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="ITINKOI-DW0061"><DocLocation><![CDATA[C:\AutomationRegressionSuite_V2.0\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res8]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default_0.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Excel Sheet Import]]></Obj>
<Details ><![CDATA[Excel Sheet  Applications Import to Applications operation Done Succefully]]></Details>
<Time><![CDATA[7/21/2015 - 8:45:25]]></Time>
<TimeTick>1437461125</TimeTick>
<NodeArgs eType="User" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Excel Sheet Import]]></Disp>
</NodeArgs>
</Step>
<Action rID="T4">
<AName><![CDATA[Driver]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ IKEA ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/21/2015 - 8:45:26]]></Time>
<TimeTick>1437461126</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" >
<Disp><![CDATA[[ IKEA ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ IKEA ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/21/2015 - 8:45:26]]></Time>
<TimeTick>1437461126</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" >
<Disp><![CDATA[[ IKEA ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[7/21/2015 - 8:45:28]]></Time>
<TimeTick>1437461128</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj ><![CDATA[Excel Sheet Import]]></Obj>
<Details ><![CDATA[Excel Sheet  Global Import to Global operation Done Succefully]]></Details>
<Time><![CDATA[7/21/2015 - 8:45:28]]></Time>
<TimeTick>1437461128</TimeTick>
<NodeArgs eType="User" icon="3" nRep="12" status="Passed" >
<Disp><![CDATA[Excel Sheet Import]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:06]]></Time>
<TimeTick>1437461166</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:06]]></Time>
<TimeTick>1437461166</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[RGdeliveryMethod.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:06]]></Time>
<TimeTick>1437461166</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="16" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[RGdeliveryMethod.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="14" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[CheckObject]]></Obj>
<Details ><![CDATA[WebRadioGroup  - deliveryMethodExist]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:06]]></Time>
<TimeTick>1437461166</TimeTick>
<NodeArgs eType="User" icon="3" nRep="17" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[CheckObject]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:08]]></Time>
<TimeTick>1437461168</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:08]]></Time>
<TimeTick>1437461168</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[RGdeliveryMethod.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:08]]></Time>
<TimeTick>1437461168</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="20" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[RGdeliveryMethod.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[RGdeliveryMethod]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the RGdeliveryMethod object. Confirm that the specified item is included in the object's item collection.]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:08]]></Time>
<TimeTick>1437461168</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[RGdeliveryMethod]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>miccommentproperty = <br>Mercury Class = WebRadioGroup<br>Html Tag = INPUT<br>_xpath = //INPUT[@id="IKEA-PageModule-ShoppingBag-_Delivery-homedelivery"]<br>|Visible = -1<br>Name = deliveryMethod<br>Items Count = 2<br>Html Id = IKEA-PageModule-ShoppingBag-_Delivery-homedelivery<br>DHTML Class = <br>]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:08]]></Time>
<TimeTick>1437461168</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" status="Warning" nType="Description" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[RGdeliveryMethod]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="22" status="Failed" nType="Run Error" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[RGdeliveryMethod]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="19" status="Failed" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="18" status="Failed" Source="C:\AutomationRegressionSuite_V2.0\TestCases\Testcases.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the specified item of the RGdeliveryMethod object. Confirm that the specified item is included in the object's item collection.<BR>Function file: C:\AutomationRegressionSuite_V2.0\Resources\FunctionLibrary\ActionNavigation.txt<BR>Line (942): &quot;strPage.WebRadioGroup(strRepObj).Select strInputValue&quot;.]]></Details>
<Time><![CDATA[7/21/2015 - 8:46:08]]></Time>
<TimeTick>1437461168</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" status="Failed" Source="C:\AutomationRegressionSuite_V2.0\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="941" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/21/2015 - 8:47:11]]></Time>
<TimeTick>1437461231</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/21/2015 - 8:47:11]]></Time>
<TimeTick>1437461231</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[RGdeliveryMethod.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[7/21/2015 - 8:47:11]]></Time>
<TimeTick>1437461231</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="28" Source="C:\AutomationRegressionSuite_V2.0\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[RGdeliveryMethod.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[7/21/2015 - 8:47:34]]></Time>
<TimeTick>1437461254</TimeTick>
<NodeArgs eType="General" icon="9" nRep="29" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="27" Source="C:\AutomationRegressionSuite_V2.0\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="26" Source="C:\AutomationRegressionSuite_V2.0\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/21/2015 - 8:45:26" eTime="7/21/2015 - 8:47:34" passed="1" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Driver Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[7/21/2015 - 8:47:34]]></Time>
<TimeTick>1437461254</TimeTick>
<NodeArgs eType="General" icon="10" nRep="31" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/21/2015 - 8:45:23" eTime="7/21/2015 - 8:47:34" passed="2" failed="2" warnings="1" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>