<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="W. Europe Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="ITINKOI-DW0061"><DocLocation><![CDATA[\\PTPSEELM-NT1045.ikeadt.com\TAC\Wave 3 Automation\AutomationRegressionSuite_V2.5\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res14]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default_0.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Excel Sheet Import]]></Obj>
<Details ><![CDATA[Excel Sheet  Applications Import to Applications operation Done Succefully]]></Details>
<Time><![CDATA[9/18/2015 - 14:19:36]]></Time>
<TimeTick>1442578776</TimeTick>
<NodeArgs eType="User" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Excel Sheet Import]]></Disp>
</NodeArgs>
</Step>
<Action rID="T4">
<AName><![CDATA[Driver]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:19:38]]></Time>
<TimeTick>1442578778</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[Excel Sheet Import]]></Obj>
<Details ><![CDATA[Excel Sheet  Global Import to Global operation Done Succefully]]></Details>
<Time><![CDATA[9/18/2015 - 14:19:38]]></Time>
<TimeTick>1442578778</TimeTick>
<NodeArgs eType="User" icon="3" nRep="10" status="Passed" >
<Disp><![CDATA[Excel Sheet Import]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/18/2015 - 14:19:40]]></Time>
<TimeTick>1442578780</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/18/2015 - 14:19:40]]></Time>
<TimeTick>1442578780</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[NWPFE.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:19:40]]></Time>
<TimeTick>1442578780</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" >
<Disp><![CDATA[NWPFE.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[9/18/2015 - 14:19:41]]></Time>
<TimeTick>1442578781</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Details>
<Time><![CDATA[9/18/2015 - 14:19:41]]></Time>
<TimeTick>1442578781</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Run "firefox.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="22" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="18" status="Passed" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="17" status="Passed" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'CheckBrowserExist'<BR>Function file: \\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt<BR>Line (59): &quot;blnT = CheckBrowserExist(gApp)&quot;.]]></Details>
<Time><![CDATA[9/18/2015 - 14:20:07]]></Time>
<TimeTick>1442578807</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" status="Failed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="58" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'CheckBrowserExist'<BR>Function file: \\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt<BR>Line (59): &quot;blnT = CheckBrowserExist(gApp)&quot;.]]></Details>
<Time><![CDATA[9/18/2015 - 14:25:40]]></Time>
<TimeTick>1442579140</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" status="Failed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="58" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'CheckBrowserExist'<BR>Function file: \\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt<BR>Line (59): &quot;blnT = CheckBrowserExist(gApp)&quot;.]]></Details>
<Time><![CDATA[9/18/2015 - 14:25:47]]></Time>
<TimeTick>1442579147</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" status="Failed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="58" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[9/18/2015 - 14:25:50]]></Time>
<TimeTick>1442579150</TimeTick>
<NodeArgs eType="General" icon="9" nRep="27" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="9/18/2015 - 14:19:36" eTime="9/18/2015 - 14:25:50" passed="2" failed="3" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Driver Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="9/18/2015 - 14:19:34" eTime="9/18/2015 - 14:25:50" passed="3" failed="3" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Driver Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>