<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="W. Europe Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="ITINKOI-DW0061"><DocLocation><![CDATA[\\PTPSEELM-NT1045.ikeadt.com\TAC\Wave 3 Automation\AutomationRegressionSuite_V2.5\Driver]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Driver]]></DName>
<Res><![CDATA[Res15]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default_0.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Excel Sheet Import]]></Obj>
<Details ><![CDATA[Excel Sheet  Applications Import to Applications operation Done Succefully]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:12]]></Time>
<TimeTick>1442579172</TimeTick>
<NodeArgs eType="User" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Excel Sheet Import]]></Disp>
</NodeArgs>
</Step>
<Action rID="T4">
<AName><![CDATA[Driver]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:13]]></Time>
<TimeTick>1442579173</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj ><![CDATA[Excel Sheet Import]]></Obj>
<Details ><![CDATA[Excel Sheet  Global Import to Global operation Done Succefully]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:13]]></Time>
<TimeTick>1442579173</TimeTick>
<NodeArgs eType="User" icon="3" nRep="10" status="Passed" >
<Disp><![CDATA[Excel Sheet Import]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:16]]></Time>
<TimeTick>1442579176</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:16]]></Time>
<TimeTick>1442579176</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[NWPFE.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:16]]></Time>
<TimeTick>1442579176</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" >
<Disp><![CDATA[NWPFE.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:16]]></Time>
<TimeTick>1442579176</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:16]]></Time>
<TimeTick>1442579176</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="23" status="Passed" >
<Disp><![CDATA[Run "firefox.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="22" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="18" status="Passed" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="17" status="Passed" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'CheckBrowserExist'<BR>Function file: \\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt<BR>Line (59): &quot;blnT = CheckBrowserExist(gApp)&quot;.]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:41]]></Time>
<TimeTick>1442579201</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" status="Failed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="58" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:48]]></Time>
<TimeTick>1442579208</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[NWPFE.Refresh All Tabs]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:48]]></Time>
<TimeTick>1442579208</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="27" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE.Refresh All Tabs]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:51]]></Time>
<TimeTick>1442579211</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Link ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:51]]></Time>
<TimeTick>1442579211</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="51" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ Link ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ United Kingdom (en) ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:51]]></Time>
<TimeTick>1442579211</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="52" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ United Kingdom (en) ].Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="50" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="26" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj ><![CDATA[FE_ClickOn_Link]]></Obj>
<Details ><![CDATA[United Kingdom (en) link verified successfully.]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:51]]></Time>
<TimeTick>1442579211</TimeTick>
<NodeArgs eType="User" icon="3" nRep="54" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[FE_ClickOn_Link]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ United Kingdom (en) ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:51]]></Time>
<TimeTick>1442579211</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="56" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ United Kingdom (en) ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:59]]></Time>
<TimeTick>1442579219</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:59]]></Time>
<TimeTick>1442579219</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[NWPFE.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/18/2015 - 14:26:59]]></Time>
<TimeTick>1442579219</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="61" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="60" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="59" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[FE_ClickOn_Link]]></Obj>
<Details ><![CDATA[United Kingdom (en) link clicked successfully.]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:03]]></Time>
<TimeTick>1442579223</TimeTick>
<NodeArgs eType="User" icon="3" nRep="62" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[FE_ClickOn_Link]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[FE_ClickOn_Link]]></Obj>
<Details ><![CDATA[ All links clicked successfully.]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:03]]></Time>
<TimeTick>1442579223</TimeTick>
<NodeArgs eType="User" icon="3" nRep="63" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[FE_ClickOn_Link]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Subscript out of range: '[number: 0]'<BR>Function file: \\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt<BR>Line (9342): &quot;blnT=FE_ClickOn_Link(arrLinktoClick(0))&quot;.]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:03]]></Time>
<TimeTick>1442579223</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="64" status="Failed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="9341" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:11]]></Time>
<TimeTick>1442579231</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:11]]></Time>
<TimeTick>1442579231</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[NWPFE.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:11]]></Time>
<TimeTick>1442579231</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="69" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="68" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="67" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Subscript out of range: '[number: 1]'<BR>Function file: \\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt<BR>Line (9351): &quot;blnT=FE_Verify_Link_Exist(arrLinktoClick(1))&quot;.]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:15]]></Time>
<TimeTick>1442579235</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="70" status="Failed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="9350" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Verify if the login page is loaded]]></Obj>
<Details ><![CDATA[ Login page is not loaded]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:18]]></Time>
<TimeTick>1442579238</TimeTick>
<NodeArgs eType="User" icon="3" nRep="71" status="Warning" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[Verify if the login page is loaded]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:18]]></Time>
<TimeTick>1442579238</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:18]]></Time>
<TimeTick>1442579238</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[NWPFE.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:18]]></Time>
<TimeTick>1442579238</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="76" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="75" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="74" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[TS_Wave3_NWP_ST_FE_Positive_15031_Orderconfirmationemail_RC status]]></Obj>
<Details ><![CDATA[Order is  Not placed successfully]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:26]]></Time>
<TimeTick>1442579246</TimeTick>
<NodeArgs eType="User" icon="3" nRep="77" status="Warning" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[TS_Wave3_NWP_ST_FE_Positive_15031_Orderconfirmationemail_RC status]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj ><![CDATA[CaptureScreen]]></Obj>
<Details ><![CDATA[Application Error Snapshot]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:26]]></Time>
<TimeTick>1442579246</TimeTick>
<NodeArgs eType="User" icon="3" nRep="78" status="Warning" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[CaptureScreen]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act0\Row0\ssf1.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj ><![CDATA[TS_Wave3_NWP_ST_FE_Positive_15031_Orderconfirmationemail_RC]]></Obj>
<Details ><![CDATA[FAIL]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:26]]></Time>
<TimeTick>1442579246</TimeTick>
<NodeArgs eType="User" icon="3" nRep="79" status="Failed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[TS_Wave3_NWP_ST_FE_Positive_15031_Orderconfirmationemail_RC]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ en_GB Home Content - IKEA ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:28]]></Time>
<TimeTick>1442579248</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="80" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ en_GB Home Content - IKEA ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ en_GB Home Content - IKEA ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:28]]></Time>
<TimeTick>1442579248</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="81" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ en_GB Home Content - IKEA ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:29]]></Time>
<TimeTick>1442579249</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="83" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:32]]></Time>
<TimeTick>1442579252</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:32]]></Time>
<TimeTick>1442579252</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[NWPFE.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:32]]></Time>
<TimeTick>1442579252</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="92" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:33]]></Time>
<TimeTick>1442579253</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:33]]></Time>
<TimeTick>1442579253</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="96" status="Passed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[Run "firefox.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="95" status="Passed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="91" status="Passed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="90" status="Passed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Verifying the errors]]></Obj>
<Details ><![CDATA[Error encountered: Type mismatch]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:58]]></Time>
<TimeTick>1442579278</TimeTick>
<NodeArgs eType="User" icon="3" nRep="97" status="Warning" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[Verifying the errors]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj ><![CDATA[CaptureScreen]]></Obj>
<Details ><![CDATA[Application Error Snapshot]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:58]]></Time>
<TimeTick>1442579278</TimeTick>
<NodeArgs eType="User" icon="3" nRep="98" status="Warning" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[CaptureScreen]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act0\Row0\ssf2.xml]]></Path>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj ><![CDATA[TS_Wave3_NWP_ST_FE_7189_ViewTermsAndConditions]]></Obj>
<Details ><![CDATA[FAIL]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:58]]></Time>
<TimeTick>1442579278</TimeTick>
<NodeArgs eType="User" icon="3" nRep="99" status="Failed" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[TS_Wave3_NWP_ST_FE_7189_ViewTermsAndConditions]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:59]]></Time>
<TimeTick>1442579279</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="100" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[9/18/2015 - 14:27:59]]></Time>
<TimeTick>1442579279</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="101" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ Browser ].Close]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Browser ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:28:01]]></Time>
<TimeTick>1442579281</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="103" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[[ Browser ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[9/18/2015 - 14:28:03]]></Time>
<TimeTick>1442579283</TimeTick>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[NWPFE]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[9/18/2015 - 14:28:03]]></Time>
<TimeTick>1442579283</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[NWPFE.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[9/18/2015 - 14:28:03]]></Time>
<TimeTick>1442579283</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="112" Source="\\PTPSEELM-NT1045.ikeadt.com\Share\TAC\Wave 3 Automation\NWP Demo\AutomationRegressionSuite_V2.4\Resources\FunctionLibrary\ActionNavigation.txt" SourceLine="-1" >
<Disp><![CDATA[NWPFE.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[9/18/2015 - 14:28:04]]></Time>
<TimeTick>1442579284</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "firefox.exe",1]]></Details>
<Time><![CDATA[9/18/2015 - 14:28:04]]></Time>
<TimeTick>1442579284</TimeTick>